# Generated by Django 5.1.5 on 2025-01-17 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_service_app', '0002_rename_contactmessage_contact_alter_booking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='user',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
